// Existing code...

const defaultBlockedDomains = [
    // Other domains...
    "pwc.ch",
    "bdo.ch",
    "ey.com",
    "kpmg.ch",
    "deloitte.ch",
    "taxpartner.ch",
    "mazars.ch",
    "grantthornton.ch",
    "pkf.swiss",
    "obt.ch",
    "kendris.com",
    "balmer-etienne.ch",
    "caminada.com",
    "fidinam.com",
    "fidag-sa.ch",
    "rister.ch",
    "findea.ch",
    "fidulex.ch",
    "entreprendre.ch",
    "acctive.ch",
    "fbk-conseils.ch",
    "karpeo.ch",
    "safe-fiduciaire.ch",
    "berneyassocies.com",
    "alltax.ch",
    "omnitax.ch",
    "retax.ch",
    "wadsack.ch",
    "core-partner.ch",
    "adbtax.ch",
    "cofidest.ch",
    "cofidest-swiss-audit.ch",
    "tax-services.ch",
    "eurexsuisse.com",
    "ftrust.ch",
    "aaretax.ch",
    "aapartnertreuhand.ch",
    "ackermann-treuhand.ch",
    "treuco.ch",
    "rnptreuhand.ch",
    "nexova.ch",
    "financialkeepers.ch",
    "fg-fiduciaire.ch",
    "roux-associes.ch",
    "fidurolle.ch",
    "zuffereypanigas.ch",
    "fiduciaire-rutz-menger.ch",
    "grf-societe-fiduciaire.ch",
    "y-fiduciaire.ch",
    "fiducom.ch",
    "swissdomiciliation.ch",
    "liberal-vd.ch",
    "kaurum.com",
    "finwise.ch",
    "calliopee.ch",
    "agfiduciaire.ch",
    "aag-fiduciaire.ch",
    "mm-t.ch",
    "gtf.ch",
    "bbtreuhand.ch",
    "dlg.ch"
];

// Existing code continues...